module.exports = [
    { code: "AFN", name: "Afghan Afghani", symbol: "؋" },
    { code: "ALL", name: "Albanian Lek", symbol: "Lek" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج.‏" },
    { code: "ARS", name: "Argentine Peso", symbol: "$" },
    { code: "AMD", name: "Armenian Dram", symbol: "դր." },
    { code: "AUD", name: "Australian Dollar", symbol: "$" },
    { code: "AZN", name: "Azerbaijani Manat", symbol: "ман." },
    { code: "BHD", name: "Bahraini Dinar", symbol: "د.ب.‏" },
    { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
    { code: "BYN", name: "Belarusian Ruble", symbol: "руб." },
    { code: "BZD", name: "Belize Dollar", symbol: "$" },
    { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs" },
    { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM" },
    { code: "BWP", name: "Botswanan Pula", symbol: "P" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "GBP", name: "British Pound", symbol: "£" },
    { code: "BND", name: "Brunei Dollar", symbol: "$" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв." },
    { code: "BIF", name: "Burundian Franc", symbol: "FBu" },
    { code: "KHR", name: "Cambodian Riel", symbol: "៛" },
    { code: "CAD", name: "Canadian Dollar", symbol: "$" },
    { code: "CVE", name: "Cape Verdean Escudo", symbol: "CV$" },
    { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA" },
    { code: "CLP", name: "Chilean Peso", symbol: "$" },
    { code: "CNY", name: "Chinese Yuan", symbol: "CN¥" },
    { code: "COP", name: "Colombian Peso", symbol: "$" },
    { code: "KMF", name: "Comorian Franc", symbol: "FC" },
    { code: "CDF", name: "Congolese Franc", symbol: "FrCD" },
    { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { code: "DKK", name: "Danish Krone", symbol: "kr" },
    { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj" },
    { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
    { code: "EGP", name: "Egyptian Pound", symbol: "ج.م.‏" },
    { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk" },
    { code: "EEK", name: "Estonian Kroon", symbol: "kr" },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "GEL", name: "Georgian Lari", symbol: "GEL" },
    { code: "GHS", name: "Ghanaian Cedi", symbol: "GH₵" },
    { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
    { code: "GNF", name: "Guinean Franc", symbol: "FG" },
    { code: "HNL", name: "Honduran Lempira", symbol: "L" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "$" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr" },
    { code: "INR", name: "Indian Rupee", symbol: "টকা" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
    { code: "IRR", name: "Iranian Rial", symbol: "﷼" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "د.ع.‏" },
    { code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "$" },
    { code: "JPY", name: "Japanese Yen", symbol: "￥" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "د.أ.‏" },
    { code: "KZT", name: "Kazakhstani Tenge", symbol: "тңг." },
    { code: "KES", name: "Kenyan Shilling", symbol: "Ksh" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك.‏" },
    { code: "LVL", name: "Latvian Lats", symbol: "Ls" },
    { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل.‏" },
    { code: "LYD", name: "Libyan Dinar", symbol: "د.ل.‏" },
    { code: "LTL", name: "Lithuanian Litas", symbol: "Lt" },
    { code: "MOP", name: "Macanese Pataca", symbol: "MOP$" },
    { code: "MKD", name: "Macedonian Denar", symbol: "MKD" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "MGA" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "MUR", name: "Mauritian Rupee", symbol: "MURs" },
    { code: "MXN", name: "Mexican Peso", symbol: "$" },
    { code: "MDL", name: "Moldovan Leu", symbol: "MDL" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.‏" },
    { code: "MZN", name: "Mozambican Metical", symbol: "MTn" },
    { code: "MMK", name: "Myanmar Kyat", symbol: "K" },
    { code: "NAD", name: "Namibian Dollar", symbol: "N$" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "नेरू" },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$" },
    { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
    { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "OMR", name: "Omani Rial", symbol: "ر.ع.‏" },
    { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
    { code: "PAB", name: "Panamanian Balboa", symbol: "B/." },
    { code: "PYG", name: "Paraguayan Guarani", symbol: "₲" },
    { code: "PEN", name: "Peruvian Sol", symbol: "S/." },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł" },
    { code: "QAR", name: "Qatari Rial", symbol: "ر.ق.‏" },
    { code: "RON", name: "Romanian Leu", symbol: "RON" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽." },
    { code: "RWF", name: "Rwandan Franc", symbol: "FR" },
    { code: "SAR", name: "Saudi Riyal", symbol: "ر.س.‏" },
    { code: "RSD", name: "Serbian Dinar", symbol: "дин." },
    { code: "SGD", name: "Singapore Dollar", symbol: "$" },
    { code: "SOS", name: "Somali Shilling", symbol: "Ssh" },
    { code: "ZAR", name: "South African Rand", symbol: "R" },
    { code: "KRW", name: "South Korean Won", symbol: "₩" },
    { code: "LKR", name: "Sri Lankan Rupee", symbol: "SL Re" },
    { code: "SDG", name: "Sudanese Pound", symbol: "SDG" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
    { code: "SYP", name: "Syrian Pound", symbol: "ل.س.‏" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
    { code: "THB", name: "Thai Baht", symbol: "฿" },
    { code: "TOP", name: "Tongan Paʻanga", symbol: "T$" },
    { code: "TTD", name: "Trinidad & Tobago Dollar", symbol: "$" },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت.‏" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "UGX", name: "Ugandan Shilling", symbol: "USh" },
    { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
    { code: "AED", name: "United Arab Emirates Dirham", symbol: "د.إ.‏" },
    { code: "UYU", name: "Uruguayan Peso", symbol: "$" },
    { code: "UZS", name: "Uzbekistani Som", symbol: "UZS" },
    { code: "VEF", name: "Venezuelan Bolívar", symbol: "Bs.F." },
    { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
    { code: "XOF", name: "West African CFA Franc", symbol: "CFA" },
    { code: "YER", name: "Yemeni Rial", symbol: "ر.ي.‏" },
    { code: "ZMK", name: "Zambian Kwacha", symbol: "ZK" },
    { code: "ZWL", name: "Zimbabwean Dollar", symbol: "ZWL$" }
]