module.exports = [
    { code: "AFN", name: "Afghani", symbol: "؋" },
    { code: "ALL", name: "Lek", symbol: "Lekë" },
    { code: "DZD", name: "Algerian Dinar", symbol: "د.ج.‏" },
    { code: "USD", name: "US Dollar", symbol: "$" },
    { code: "EUR", name: "Euro", symbol: "€" },
    { code: "AOA", name: "Kwanza", symbol: "Kz" },
    { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$" },
    { code: "ARS", name: "Argentine Peso", symbol: "$" },
    { code: "AMD", name: "Armenian Dram", symbol: "֏" },
    { code: "AWG", name: "Aruban Florin", symbol: "Afl." },
    { code: "AUD", name: "Australian Dollar", symbol: "$" },
    { code: "AZN", name: "Azerbaijanian Manat", symbol: "₼" },
    { code: "BSD", name: "Bahamian Dollar", symbol: "$" },
    { code: "BHD", name: "Bahraini Dinar", symbol: "د.ب.‏" },
    { code: "BDT", name: "Taka", symbol: "৳" },
    { code: "BBD", name: "Barbados Dollar", symbol: "$" },
    { code: "BYN", name: "Belarussian Ruble", symbol: "Br" },
    { code: "BZD", name: "Belize Dollar", symbol: "$" },
    { code: "XOF", name: "CFA Franc BCEAO", symbol: "CFA" },
    { code: "BMD", name: "Bermudian Dollar", symbol: "$" },
    { code: "BTN", name: "Ngultrum", symbol: "Nu." },
    { code: "INR", name: "Indian Rupee", symbol: "₹" },
    { code: "BOB", name: "Boliviano", symbol: "Bs" },
    { code: "BAM", name: "Convertible Mark", symbol: "КМ" },
    { code: "BWP", name: "Pula", symbol: "P" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$" },
    { code: "BND", name: "Brunei Dollar", symbol: "$" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв." },
    { code: "BIF", name: "Burundi Franc", symbol: "FBu" },
    { code: "CVE", name: "Cabo Verde Escudo", symbol: "" },
    { code: "KHR", name: "Riel", symbol: "៛" },
    { code: "XAF", name: "CFA Franc BEAC", symbol: "FCFA" },
    { code: "CAD", name: "Canadian Dollar", symbol: "$" },
    { code: "KYD", name: "Cayman Islands Dollar", symbol: "$" },
    { code: "CLF", name: "Unidad de Fomento", symbol: "" },
    { code: "CLP", name: "Chilean Peso", symbol: "$" },
    { code: "CNY", name: "Yuan Renminbi", symbol: "¥" },
    { code: "COP", name: "Colombian Peso", symbol: "$" },
    { code: "KMF", name: "Comoro Franc", symbol: "CF" },
    { code: "CDF", name: "Congolese Franc", symbol: "FC" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$" },
    { code: "CRC", name: "Costa Rican Colon", symbol: "₡" },
    { code: "HRK", name: "Kuna", symbol: "kn" },
    { code: "CUC", name: "Peso Convertible", symbol: "" },
    { code: "CUP", name: "Cuban Peso", symbol: "$" },
    { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "NAf." },
    { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
    { code: "DKK", name: "Danish Krone", symbol: "kr." },
    { code: "DJF", name: "Djibouti Franc", symbol: "Fdj" },
    { code: "DOP", name: "Dominican Peso", symbol: "$" },
    { code: "EGP", name: "Egyptian Pound", symbol: "ج.م.‏" },
    { code: "SVC", name: "El Salvador Colon", symbol: "" },
    { code: "ERN", name: "Nakfa", symbol: "Nfk" },
    { code: "ETB", name: "Ethiopian Birr", symbol: "Br" },
    { code: "FKP", name: "Falkland Islands Pound", symbol: "£" },
    { code: "FJD", name: "Fiji Dollar", symbol: "$" },
    { code: "XPF", name: "CFP Franc", symbol: "FCFP" },
    { code: "GMD", name: "Dalasi", symbol: "D" },
    { code: "GEL", name: "Lari", symbol: "₾" },
    { code: "GHS", name: "Ghana Cedi", symbol: "GH₵" },
    { code: "GIP", name: "Gibraltar Pound", symbol: "£" },
    { code: "GTQ", name: "Quetzal", symbol: "Q" },
    { code: "GBP", name: "British Pound Sterling", symbol: "£" },
    { code: "GNF", name: "Guinea Franc", symbol: "FG" },
    { code: "GYD", name: "Guyana Dollar", symbol: "$" },
    { code: "HTG", name: "Gourde", symbol: "G" },
    { code: "HNL", name: "Lempira", symbol: "L" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "$" },
    { code: "HUF", name: "Forint", symbol: "Ft" },
    { code: "ISK", name: "Iceland Krona", symbol: "kr" },
    { code: "IDR", name: "Rupiah", symbol: "Rp" },
    { code: "XDR", name: "SDR (Special Drawing Right)", symbol: "XDR" },
    { code: "IRR", name: "Iranian Rial", symbol: "ريال" },
    { code: "IQD", name: "Iraqi Dinar", symbol: "د.ع.‏" },
    { code: "ILS", name: "New Israeli Sheqel", symbol: "₪" },
    { code: "JMD", name: "Jamaican Dollar", symbol: "$" },
    { code: "JPY", name: "Yen", symbol: "¥" },
    { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا.‏" },
    { code: "KZT", name: "Tenge", symbol: "₸" },
    { code: "KES", name: "Kenyan Shilling", symbol: "Ksh" },
    { code: "KPW", name: "North Korean Won", symbol: "₩" },
    { code: "KRW", name: "Won", symbol: "₩" },
    { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك.‏" },
    { code: "KGS", name: "Som", symbol: "сом" },
    { code: "LAK", name: "Kip", symbol: "₭" },
    { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل.‏" },
    { code: "LSL", name: "Loti", symbol: "" },
    { code: "ZAR", name: "Rand", symbol: "R" },
    { code: "LRD", name: "Liberian Dollar", symbol: "$" },
    { code: "LYD", name: "Libyan Dinar", symbol: "د.ل.‏" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
    { code: "MOP", name: "Pataca", symbol: "MOP$" },
    { code: "MGA", name: "Malagasy Ariary", symbol: "Ar" },
    { code: "MWK", name: "Kwacha", symbol: "MK" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
    { code: "MVR", name: "Rufiyaa", symbol: "ރ." },
    { code: "MUR", name: "Mauritius Rupee", symbol: "Rs" },
    { code: "MXN", name: "Mexican Peso", symbol: "$" },
    { code: "MDL", name: "Moldovan Leu", symbol: "L" },
    { code: "MNT", name: "Tugrik", symbol: "₮" },
    { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.‏" },
    { code: "MZN", name: "Mozambique Metical", symbol: "MTn" },
    { code: "MMK", name: "Kyat", symbol: "K" },
    { code: "NAD", name: "Namibia Dollar", symbol: "$" },
    { code: "NPR", name: "Nepalese Rupee", symbol: "रु" },
    { code: "NIO", name: "Cordoba Oro", symbol: "C$" },
    { code: "NGN", name: "Naira", symbol: "₦" },
    { code: "OMR", name: "Rial Omani", symbol: "ر.ع.‏" },
    { code: "PKR", name: "Pakistan Rupee", symbol: "Rs" },
    { code: "PAB", name: "Balboa", symbol: "B/." },
    { code: "PGK", name: "Kina", symbol: "K" },
    { code: "PYG", name: "Guarani", symbol: "₲" },
    { code: "PEN", name: "Nuevo Sol", symbol: "S/" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱" },
    { code: "PLN", name: "Zloty", symbol: "zł" },
    { code: "QAR", name: "Qatari Rial", symbol: "ر.ق.‏" },
    { code: "MKD", name: "Denar", symbol: "ден" },
    { code: "RON", name: "Romanian Leu", symbol: "lei" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽" },
    { code: "RWF", name: "Rwanda Franc", symbol: "RF" },
    { code: "SHP", name: "Saint Helena Pound", symbol: "£" },
    { code: "WST", name: "Tala", symbol: "WS$" },
    { code: "SAR", name: "Saudi Riyal", symbol: "ر.س.‏" },
    { code: "RSD", name: "Serbian Dinar", symbol: "дин." },
    { code: "SCR", name: "Seychelles Rupee", symbol: "SR" },
    { code: "SLL", name: "Leone", symbol: "Le" },
    { code: "SGD", name: "Singapore Dollar", symbol: "$" },
    { code: "SBD", name: "Solomon Islands Dollar", symbol: "$" },
    { code: "SOS", name: "Somali Shilling", symbol: "S" },
    { code: "LKR", name: "Sri Lanka Rupee", symbol: "රු." },
    { code: "SDG", name: "Sudanese Pound", symbol: "ج.س." },
    { code: "SRD", name: "Surinam Dollar", symbol: "$" },
    { code: "SZL", name: "Lilangeni", symbol: "E" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr" },
    { code: "SYP", name: "Syrian Pound", symbol: "ل.س.‏" },
    { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
    { code: "TJS", name: "Somoni", symbol: "смн" },
    { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh" },
    { code: "THB", name: "Baht", symbol: "฿" },
    { code: "TOP", name: "Pa'anga", symbol: "T$" },
    { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "$" },
    { code: "TND", name: "Tunisian Dinar", symbol: "د.ت.‏" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺" },
    { code: "TMT", name: "Turkmenistan New Manat", symbol: "m." },
    { code: "UGX", name: "Uganda Shilling", symbol: "USh" },
    { code: "UAH", name: "Hryvnia", symbol: "₴" },
    { code: "AED", name: "UAE Dirham", symbol: "د.إ.‏" },
    { code: "UYU", name: "Peso Uruguayo", symbol: "$" },
    { code: "UZS", name: "Uzbekistan Sum", symbol: "сўм" },
    { code: "VUV", name: "Vatu", symbol: "VT" },
    { code: "VND", name: "Dong", symbol: "₫" },
    { code: "YER", name: "Yemeni Rial", symbol: "ر.ي.‏" },
    { code: "ZMW", name: "Zambian Kwacha", symbol: "K" },
    { code: "ZWL", name: "Zimbabwe Dollar", symbol: "" }
]